[hypervisor]
# Replace with your hypervisor server IP and username
workstation ansible_host=192.168.1.X ansible_user=tp24 ansible_ssh_private_key_file=~/.ssh/id_ed25519

[eve_vm]
# EVE-NG virtual machine (accessible via hypervisor port 2222 or internal IP)
eve_instance ansible_host=192.168.1.X ansible_port=2222 ansible_user=root ansible_ssh_pass=eve

[soc_sensor]
# Machine hosting Suricata IDS and EveBox Dashboard
sensor_node ansible_host=127.0.0.1 ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
